name: Home Assistant app lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: frenck/action-addon-linter@v2.21
        with:
          path: ./easun_bridge
